version: '3.8'


services:
    
    nginx:
        image: nginx:1.19-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

    api:
        image: node:14.14-alpine
        volumes:
            - ./api/:/app/
        working_dir: /app/
        command: sh -c "yarn install && yarn start"
        
        
    web:
        image: node:14.14-alpine
        volumes:
            - ./web/:/app/
        working_dir: /app/
        command: sh -c "yarn install && yarn start"
        
    mongo:
        image: mongo:4.4
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
            
    mongo_express:
        image: mongo-express
        environment:
            ME_CONFIG_SITE_BASEURL: /mongo
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: username
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            
        
