version: '3.8'


services:
    
    nginx:
        image: nginx:1.19-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

    api:
        image: node:14.14-alpine
        volumes:
            - ./api/:/app/
        working_dir: /app/
        command: yarn start
        
        
